
services:
  web:
    image: nginx
    ports:
      - "80:80"

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: userinfo
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
# docker-compose up(Builds, (re)creates, starts, and attaches to containers for a service)
# docker-compose up -d
# docker-compose down(: Stops and removes the containers, networks, volumes, and images )

